In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from sklearn.datasets import make_classification

In [5]:
##create the datsets 
X,y=make_classification(n_samples=1000,n_features=10,n_classes=2,random_state=42)

In [6]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.30,random_state=42)

In [7]:
#model training 
from sklearn.linear_model import LogisticRegression
logistic=LogisticRegression()

In [8]:
logistic.fit(X_train,y_train)

LogisticRegression()

In [9]:
y_pred=logistic.predict(X_test)

In [11]:
logistic.predict_proba(X_test)

array([[7.74477909e-01, 2.25522091e-01],
       [3.36684957e-02, 9.66331504e-01],
       [6.70682154e-01, 3.29317846e-01],
       [7.98668032e-02, 9.20133197e-01],
       [9.76616650e-01, 2.33833501e-02],
       [4.13572804e-02, 9.58642720e-01],
       [9.79028767e-01, 2.09712329e-02],
       [9.59367261e-01, 4.06327393e-02],
       [8.08520049e-01, 1.91479951e-01],
       [6.84954318e-01, 3.15045682e-01],
       [9.13669448e-01, 8.63305524e-02],
       [2.63597018e-01, 7.36402982e-01],
       [5.25844192e-01, 4.74155808e-01],
       [2.11912354e-01, 7.88087646e-01],
       [7.93592056e-01, 2.06407944e-01],
       [9.46621678e-01, 5.33783219e-02],
       [2.62957933e-02, 9.73704207e-01],
       [3.24212617e-01, 6.75787383e-01],
       [3.14803584e-01, 6.85196416e-01],
       [2.04956217e-01, 7.95043783e-01],
       [5.04587065e-01, 4.95412935e-01],
       [9.66703630e-01, 3.32963696e-02],
       [2.00514796e-01, 7.99485204e-01],
       [7.77891908e-01, 2.22108092e-01],
       [8.729863

In [12]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [23]:
score=accuracy_score(y_test,y_pred)
print(score)
cm= confusion_matrix(y_test,y_pred)
print(cm)
print(classification_report(y_test,y_pred))


0.8466666666666667
[[118  17]
 [ 29 136]]
              precision    recall  f1-score   support

           0       0.80      0.87      0.84       135
           1       0.89      0.82      0.86       165

    accuracy                           0.85       300
   macro avg       0.85      0.85      0.85       300
weighted avg       0.85      0.85      0.85       300



Hyperparameter Tuning And Cross validation


In [24]:
model=LogisticRegression()
penalty=['11','12','elasticnet']
c_values=[100,10,1.0,0.1,0.01]
solver=['newton-cg','ibfgs','libinear','sag','saga']


In [25]:
param=dict(penalty=penalty,C=c_values,solver=solver)

In [26]:
from sklearn.model_selection import StratifiedGroupKFold
cv=StratifiedGroupKFold

In [34]:
##grid search cv
from sklearn.model_selection import GridSearchCV

grid=GridSearchCV(estimator=model,param_grid=param,scoring='accuracy_score',cv=cv,n_jobs=-1)

In [35]:
grid

GridSearchCV(cv=<class 'sklearn.model_selection._split.StratifiedGroupKFold'>,
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1.0, 0.1, 0.01],
                         'penalty': ['11', '12', 'elasticnet'],
                         'solver': ['newton-cg', 'ibfgs', 'libinear', 'sag',
                                    'saga']},
             scoring='accuracy_score')

In [36]:
# grid.fit(X_train,y_train)
grid.best_params_

AttributeError: 'GridSearchCV' object has no attribute 'best_params_'

In [37]:
from sklearn.model_selection import RandomizedSearchCV

Randomsed cv


In [38]:
model= LogisticRegression()
random= RandomizedSearchCV(estimator=model,param_distributions=param,cv=5,scoring='accuracy_score')

In [41]:
X,y=make_classification(n_samples=1000,n_features=10,n_classes=3,n_informative=3,random_state=42)

array([[ 0.7715326 , -1.47433614,  2.19664605, ...,  0.68174341,
         1.08996189,  0.96250289],
       [ 1.85838284, -3.68087983,  0.22749588, ..., -0.47417818,
         1.34113888, -0.77177196],
       [-0.98724764,  1.53916836,  0.5859042 , ..., -0.32202815,
        -1.45103394,  1.32543211],
       ...,
       [-1.227082  ,  1.65602784,  0.47263035, ..., -0.8634936 ,
        -1.83932326, -0.03120349],
       [ 1.28527572, -0.29715202, -0.67172079, ..., -1.31544131,
         2.85446468,  1.3094441 ],
       [-0.75428048,  0.88516075, -1.6728939 , ..., -2.0362205 ,
        -1.43989584,  0.04749347]], shape=(1000, 10))

In [43]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.30,random_state=42)

In [55]:
from sklearn.linear_model import LogisticRegression
logistic=LogisticRegression(multi_class='ovr')
logistic.fit(X_train,y_train)
y_pred=logistic.predict(X_test)

c:\Users\pranav\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(


In [57]:
score=accuracy_score(y_test,y_pred)
print(score)
cm= confusion_matrix(y_test,y_pred)
print(cm)
print(classification_report(y_test,y_pred))

0.9892
[[2465    0]
 [  27    8]]
              precision    recall  f1-score   support

           0       0.99      1.00      0.99      2465
           1       1.00      0.23      0.37        35

    accuracy                           0.99      2500
   macro avg       0.99      0.61      0.68      2500
weighted avg       0.99      0.99      0.99      2500



imbalanced dataset


In [47]:
from collections import Counter 
from sklearn.datasets import make_classification

In [48]:
X,y=make_classification(n_samples=10000,n_features=2,n_clusters_per_class=1,
                        n_redundant=0,weights=[0.99],random_state=10)

In [49]:
X

array([[ 1.87991016, -1.4850347 ],
       [ 0.37708311, -2.23858488],
       [ 1.35431163, -2.66463822],
       ...,
       [ 0.99509904, -0.54192355],
       [ 1.75859359, -1.54961188],
       [ 0.79770543, -1.99467372]], shape=(10000, 2))

In [50]:
Counter(y)

Counter({np.int64(0): 9846, np.int64(1): 154})

In [52]:
import seaborn as sns
import pandas as pd 
sns.scatterplot(pd.DataFrame(X)[0],pd.DataFrame(X)[1],hue=y)

TypeError: scatterplot() takes from 0 to 1 positional arguments but 2 positional arguments (and 1 keyword-only argument) were given

In [53]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=42)